### ISSUE TITLE
UnicodeDecodeError in graph_from_xml on Windows Installations

### ISSUE THREAD

**Issue by jonnyhuck** [gboeing/osmnx#1083]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Windows 10 / Python 3.12 (also observed in Windows 11 and Python 3.10 and 3.11)

### What OSMnx version are you using?

1.7.1

### Environment packages and versions

```shell
# Name                    Version                   Build  Channel
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
blosc                     1.21.5               hdccc3a2_0    conda-forge
branca                    0.7.0              pyhd8ed1ab_1    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0           py312h53d5487_1    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cfitsio                   4.3.0                h9b0cee5_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py312h0d7def4_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
fiona                     1.9.5           py312he9aeaab_0    conda-forge
folium                    0.15.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.44.3          py312he70551f_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    2.0.0                h8276f4a_0    conda-forge
gdal                      3.7.3           py312hb5f3cee_5    conda-forge
geopandas                 0.14.1             pyhd8ed1ab_0    conda-forge
geopandas-base            0.14.1             pyha770c72_0    conda-forge
geos                      3.12.0               h1537add_0    conda-forge
geotiff                   1.7.1               hcf4a93f_14    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.2          nompi_h73e8ff5_100    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50497    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
kealib                    1.5.2                ha10e780_1    conda-forge
kiwisolver                1.4.5           py312h0d7def4_1    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.15                 h67d730c_3    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.1.2                h63175ca_1    conda-forge
libarchive                3.7.2                h6f8411a_0    conda-forge
libblas                   3.9.0              19_win64_mkl    conda-forge
libboost-headers          1.82.0               h57928b3_6    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              19_win64_mkl    conda-forge
libcurl                   8.4.0                hd5e4a3a_0    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.7.3                h3f0de01_5    conda-forge
libglib                   2.78.1               h16e383f_1    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libkml                    1.3.0             haf3e7a6_1018    conda-forge
liblapack                 3.9.0              19_win64_mkl    conda-forge
libnetcdf                 4.9.2           nompi_h8284064_112    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     16.1                 h43585b0_0    conda-forge
librttopo                 1.1.0               h92c5fdb_14    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.1.0                hbf340bc_1    conda-forge
libsqlite                 3.44.0               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.6.0                h6e2ebb7_2    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.11.5               hc3477c8_1    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.6.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py312he70551f_1    conda-forge
matplotlib-base           3.8.1           py312h26ecaf7_0    conda-forge
minizip                   4.0.3                h5bed578_0    conda-forge
mkl                       2023.2.0         h6a75c08_50496    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     4.0.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
numpy                     1.26.0          py312h8753938_0    conda-forge
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openssl                   3.1.4                hcfcfb64_0    conda-forge
osmnx                     1.7.1              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.3           py312h2ab9e98_0    conda-forge
pcre2                     10.42                h17e33f8_0    conda-forge
pillow                    10.1.0          py312he768995_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h63175ca_0    conda-forge
poppler                   23.11.0              hc2f3c52_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.1                 hc80876b_0    conda-forge
proj                      9.3.0                he13c7e8_2    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.1           py312hb4fa1d0_4    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.12.0          h2628c8c_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
rasterio                  1.3.9           py312ha2d7edd_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rtree                     1.1.0           py312h72b5f30_0    conda-forge
scikit-learn              1.3.2           py312hcacafb1_1    conda-forge
scipy                     1.11.3          py312h8753938_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
shapely                   2.0.2           py312h92c3dd1_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.44.0               hcfcfb64_0    conda-forge
tbb                       2021.10.0            h91493d7_2    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tiledb                    2.16.3               h1ffc264_3    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
uriparser                 0.9.7                h1537add_1    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hdcecf7f_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xerces-c                  3.2.4                h63175ca_3    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xyzservices               2023.10.1          pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

### How did you install OSMnx?

Conda and conda-forge

### Problem description

# Reproduction steps

* Install osmnx on Windows machine (as per instructions)
```bash
conda create -n ox -c conda-forge --strict-channel-priority osmnx
```

* Run the following MRE (`map.osm` is just any XML export from OSM, you can reproduce with [this file](https://www.dropbox.com/scl/fi/ompxf1ayen2d9do3470lu/kaliningrad.xml?rlkey=qopb48h7rls6hpgo98ak74zx8&dl=1), but we have verified that this happens with any arbitrary export)
```python
from osmnx import graph_from_xml
graph = graph_from_xml('path_to_map.osm')
print('done!')
```
* The following error is returned, which seems to arise from the wrong character map (`cp1252`) being used to read the file (which is encoded using `utf-8`):
```
Traceback (most recent call last):
  File "c:\Users\mzdssjh8\Dropbox\Manchester\Teaching\30552-Understanding_GIS\Practicals\repos\code\ox-test.py", line 2, in <module>
    graph = graph_from_xml('C:\\Users\\mzdssjh8\\Downloads\\map.osm')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mzdssjh8\.conda\envs\ox\Lib\site-packages\osmnx\graph.py", line 559, in graph_from_xml
    response_jsons = [osm_xml._overpass_json_from_file(filepath)]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mzdssjh8\.conda\envs\ox\Lib\site-packages\osmnx\osm_xml.py", line 88, in _overpass_json_from_file
    root_attrs = ET.parse(f).getroot().attrib
                 ^^^^^^^^^^^
  File "C:\Users\mzdssjh8\.conda\envs\ox\Lib\xml\etree\ElementTree.py", line 1203, in parse
    tree.parse(source, parser)
  File "C:\Users\mzdssjh8\.conda\envs\ox\Lib\xml\etree\ElementTree.py", line 568, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mzdssjh8\.conda\envs\ox\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 44035: character maps to <undefined>
```

We can confirm that the charset in the XML is set to UTF-8:
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

We can also confirm that this error does not occur on a Mac.

### Complete minimal reproducible example

```python
from osmnx import graph_from_xml
graph = graph_from_xml('path_to_map.osm') # any Xml export from OSM see link above for example
print('done!')
```

**Comment by gboeing** [comment]
What happens when you run:

```python
import sys; print(sys.getfilesystemencoding())
import locale; print(locale.getpreferredencoding())
```

Is your OS set to use utf-8 for both of those encodings?

I thought Python on all platforms was defaulting to utf-8 since like 3.6 (see PEP 528 and 529)... but maybe it's somehow still opt-in on Windows (see PEP 540)?

**Comment by gboeing** [comment]
Here's another test for you:

```python
from pathlib import Path
with Path("kaliningrad.xml").open() as f:
    print(f)
```

The file is encoded as utf-8 and the XML declaration states that it is utf-8... does your system open it with utf-8 encoding or does it print some other encoding instead?

**Comment by jonnyhuck** [comment]
Thanks Geoff,

Interesting, those tests are quite revealing:
```python
import sys; print(f"File System Encoding: {sys.getfilesystemencoding()}")
import locale; print(f"Preferred encoding: {locale.getpreferredencoding()}")
from pathlib import Path
with Path("./data/kaliningrad/kaliningrad.xml").open() as f:
    print(f)
```
...gives...
```
File System Encoding: utf-8
Preferred encoding: cp1252
<_io.TextIOWrapper name='data\\kaliningrad\\kaliningrad.xml' mode='r' encoding='cp1252'>
```
which is clerly the source of our problem!

This error came up as part of a practical for a course at the University of Manchester - we have been running it for years and this is the first time that this has happened, I am not sure what has changed to cause it (we are seeing it across all Windoes macines that we have tried, not just a particular build etc.). Nevertheless, adding an `encoding` argument to the function as you have seems like an ideal solution - thanks for dealing with it so quickly.

**Comment by gboeing** [comment]
Great, I'll merge that PR and dream of the day when Python 3.15 arrives 🥳
