### ISSUE TITLE
AttributeError: module 'osmnx' has no attribute 'clean_intersections'

### ISSUE THREAD

**Issue by snowberkhan** [gboeing/osmnx#1097]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Ubuntu 22.04.3 LTS/Python 3.12.0

### What OSMnx version are you using?

1.8.0

### Environment packages and versions

```shell
(ox) root@9a5d20c9cb21:/# conda list
# packages in environment at /root/miniconda3/envs/ox:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
blosc                     1.21.5               h0f2a231_0    conda-forge
branca                    0.7.0              pyhd8ed1ab_1    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py312h30efb56_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.23.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cairo                     1.18.0               h3faef2a_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cfitsio                   4.3.1                hbdc6101_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
contourpy                 1.2.0           py312h8572e83_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fiona                     1.9.5           py312h66d9856_2    conda-forge
folium                    0.15.1             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.46.0          py312h98912ed_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freexl                    2.0.0                h743c826_0    conda-forge
gdal                      3.8.1           py312ha82c271_4    conda-forge
geopandas                 0.14.1             pyhd8ed1ab_0    conda-forge
geopandas-base            0.14.1             pyha770c72_0    conda-forge
geos                      3.12.1               h59595ed_0    conda-forge
geotiff                   1.7.1               h6b2125f_15    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json-c                    0.17                 h7ab15ed_0    conda-forge
kealib                    1.5.2                hcd42e92_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py312h8572e83_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libarchive                3.7.2                h2aa1ff5_1    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libboost-headers          1.83.0               ha770c72_0    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgdal                   3.8.1                hed8bd54_4    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libglib                   2.78.3               h783c2da_0    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libgoogle-cloud           2.12.0               h5206363_4    conda-forge
libgrpc                   1.59.3               hd6c4280_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
libkml                    1.3.0             h01aab08_1018    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_h9612171_113    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     16.1                 h33b98f1_7    conda-forge
libprotobuf               4.24.4               hf27288f_0    conda-forge
libre2-11                 2023.06.02           h7a70373_0    conda-forge
librttopo                 1.1.0               h8917695_15    conda-forge
libspatialindex           1.9.3                h9c3ff4c_4    conda-forge
libspatialite             5.1.0                h7bd4643_4    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.12.3               h232c23b_0    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mapclassify               2.6.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py312h98912ed_1    conda-forge
matplotlib-base           3.8.2           py312he5832f3_0    conda-forge
minizip                   4.0.3                h0ab5242_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.96                 h1d7d5a4_0    conda-forge
numpy                     1.26.2          py312heda63a1_0    conda-forge
openjpeg                  2.5.0                h488ebb8_3    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
osmnx                     1.8.0              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.4           py312hfb8ada1_0    conda-forge
pcre2                     10.42                hcad00b1_0    conda-forge
pillow                    10.1.0          py312hf3581a9_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h59595ed_0    conda-forge
poppler                   23.12.0              h590f24d_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.1                 h7387d8b_7    conda-forge
proj                      9.3.1                h1d62c97_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.1           py312h38f1c37_5    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.0          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
rasterio                  1.3.9           py312h26ef92c_2    conda-forge
re2                       2023.06.02           h2873b5e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rtree                     1.1.0           py312hb0aae1a_0    conda-forge
scikit-learn              1.3.2           py312h394d371_2    conda-forge
scipy                     1.11.4          py312heda63a1_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
shapely                   2.0.2           py312h9e6bd2c_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.44.2               h2c6b66d_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tiledb                    2.18.3               hc1131af_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzcode                    2023c                h0b41bf4_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
uriparser                 0.9.7                hcb278e6_1    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                hac6953d_3    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xyzservices               2023.10.1          pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
(ox) root@9a5d20c9cb21:/#
```

### How did you install OSMnx?

Conda and conda-forge

### Problem description

Thank you for the the amazing tool!
Im using a brand new ubuntu 22.02 VM, installed conda and OSMnx as described in https://osmnx.readthedocs.io/en/stable/installation.html

Tried to run the example on:

https://www.timlrx.com/blog/cleaning-openstreetmap-intersections-in-python

as well as the example on:

https://github.com/gboeing/osmnx-examples/blob/v0.11/notebooks/14-clean-intersection-node-clusters.ipynb

I was expecting to see a plot is the intersections for the indicated address, instead I get an error:

**I got:**

Traceback (most recent call last):
  File "/root/osmnx-test1.py", line 14, in <module>
    G = ox.graph_from_address(address, network_type='drive', distance=750)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: graph_from_address() got an unexpected keyword argument 'distance'

**After I fixed that to be dist=750, I got:**

Traceback (most recent call last):
  File "/root/osmnx-test1.py", line 16, in <module>
    fig, ax = ox.plot_graph(G, fig_height=10, node_color='orange', node_size=30,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: plot_graph() got an unexpected keyword argument 'fig_height'

**After I fixed that to be figsize=(10,10), I got:**

Traceback (most recent call last):
  File "/root/osmnx-test1.py", line 14, in <module>
    intersections = ox.clean_intersections(G_proj, tolerance=15, dead_ends=False)
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'osmnx' has no attribute 'clean_intersections'

I am running my code from the docker ubuntu container using command line:

python3 osmnx-test1.py

### Complete minimal reproducible example

```python
import matplotlib.pyplot as plt
import numpy as np
import osmnx as ox
ox.config(use_cache=True, log_console=True)
#%matplotlib inline
ox.__version__

# get a street network and plot it with all edge intersections
address = 'Franklin, TN'
G = ox.graph_from_address(address, network_type='drive', dist=750)
G_proj = ox.project_graph(G)
fig, ax = ox.plot_graph(G_proj, figsize=(10,10), node_color='orange', node_size=30,
                        node_zorder=2, node_edgecolor='k')

# clean up the intersections and extract their xy coords
intersections = ox.clean_intersections(G_proj, tolerance=15, dead_ends=False)
points = np.array([point.xy for point in intersections])

# plot the cleaned-up intersections
fig, ax = ox.plot_graph(G_proj, figsize=(10,10), show=False, close=False, node_alpha=0)
ax.scatter(x=points[:,0], y=points[:,1], zorder=2, color='#66ccff', edgecolors='k')
plt.show()
```

**Comment by snowberkhan** [comment]
Here's my entire output, you can see I activated the conda ox environment:

(ox) root@9a5d20c9cb21:/app/data/osmnx# python3 osmnx-test1.py 
/app/data/osmnx/osmnx-test1.py:4: UserWarning: The `utils.config` function is deprecated and will be removed in a future release. Instead, use the `settings` module directly to configure a global setting's value. For example, `ox.settings.log_console=True`.
  ox.config(use_cache=True, log_console=True)
2023-12-17 01:10:31 Retrieved response from cache file 'cache/81006fa43b49c3625bf52e05456106d3bdd63428.json'
2023-12-17 01:10:31 Geocoded 'Franklin, TN' to (35.1680139, -86.1084401)
2023-12-17 01:10:31 Created bbox 750 m from (35.1680139, -86.1084401): 35.174758802516195,35.1612689974838,-86.10018911733003,-86.11669108266996
2023-12-17 01:10:31 Projected GeoDataFrame to 'EPSG:32616 / WGS 84 / UTM zone 16N'
2023-12-17 01:10:31 Projected GeoDataFrame to 'EPSG:4326 / WGS 84'
2023-12-17 01:10:31 Projected GeoDataFrame to 'EPSG:32616 / WGS 84 / UTM zone 16N'
2023-12-17 01:10:31 Projected GeoDataFrame to 'EPSG:4326 / WGS 84'
2023-12-17 01:10:31 Requesting data from API in 1 request(s)
2023-12-17 01:10:31 Retrieved response from cache file 'cache/5915b94df606b1d1828c5a006d0253f1bf2b7b78.json'
2023-12-17 01:10:31 Retrieved all data from API in 1 request(s)
2023-12-17 01:10:31 Creating graph from 482 OSM nodes and 59 OSM ways...
2023-12-17 01:10:31 Created graph with 482 nodes and 920 edges
2023-12-17 01:10:31 Added length attributes to graph edges
2023-12-17 01:10:31 Identifying all nodes that lie outside the polygon...
2023-12-17 01:10:31 Created nodes GeoDataFrame from graph
2023-12-17 01:10:31 Created r-tree spatial index for 482 geometries
2023-12-17 01:10:31 Identified 305 geometries inside polygon
2023-12-17 01:10:31 Removed 177 nodes outside polygon
2023-12-17 01:10:31 Truncated graph by polygon
2023-12-17 01:10:31 Begin topologically simplifying the graph...
2023-12-17 01:10:31 Identified 81 edge endpoints
2023-12-17 01:10:31 Simplified graph: 305 to 81 nodes, 577 to 186 edges
2023-12-17 01:10:31 Identifying all nodes that lie outside the polygon...
2023-12-17 01:10:31 Created nodes GeoDataFrame from graph
2023-12-17 01:10:31 Created r-tree spatial index for 81 geometries
2023-12-17 01:10:31 Identified 19 geometries inside polygon
2023-12-17 01:10:31 Removed 62 nodes outside polygon
2023-12-17 01:10:31 Removed 1 isolated nodes
2023-12-17 01:10:31 Truncated graph by polygon
2023-12-17 01:10:31 Counted undirected street segments incident on each node
2023-12-17 01:10:31 graph_from_polygon returned graph with 18 nodes and 36 edges
2023-12-17 01:10:31 graph_from_bbox returned graph with 18 nodes and 36 edges
2023-12-17 01:10:31 graph_from_point returned graph with 18 nodes and 36 edges
2023-12-17 01:10:31 graph_from_address returned graph with 18 nodes and 36 edges
2023-12-17 01:10:31 Created nodes GeoDataFrame from graph
2023-12-17 01:10:31 Projected GeoDataFrame to 'EPSG:32616 / WGS 84 / UTM zone 16N'
2023-12-17 01:10:31 Created edges GeoDataFrame from graph
2023-12-17 01:10:31 Projected GeoDataFrame to 'EPSG:32616 / WGS 84 / UTM zone 16N'
2023-12-17 01:10:31 Created graph from node/edge GeoDataFrames
2023-12-17 01:10:31 Projected graph with 18 nodes and 36 edges
2023-12-17 01:10:31 Begin plotting the graph...
2023-12-17 01:10:31 Created edges GeoDataFrame from graph
2023-12-17 01:10:31 Created nodes GeoDataFrame from graph
2023-12-17 01:10:31 Finished plotting the graph
Traceback (most recent call last):
  File "/app/data/osmnx/osmnx-test1.py", line 16, in <module>
    intersections = ox.clean_intersections(G_proj, tolerance=15, dead_ends=False)
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'osmnx' has no attribute 'clean_intersections'
(ox) root@9a5d20c9cb21:/app/data/osmnx#

**Comment by gboeing** [comment]
The example [notebook](https://github.com/gboeing/osmnx-examples/blob/v0.11/notebooks/14-clean-intersection-node-clusters.ipynb) you said you're looking at is on the `v0.11` tag, which is several years old and uses the old v0 beta API. But you are using OSMnx v1.8.0, and thus you should look at the [corresponding](https://github.com/gboeing/osmnx-examples/blob/v1.8.0/notebooks/04-simplify-graph-consolidate-nodes.ipynb) example notebook version (or at least the current main branch of the examples repo). See also the relevant [documentation](https://osmnx.readthedocs.io/en/stable/user-reference.html#osmnx.simplification.consolidate_intersections).
