### ISSUE TITLE
error when running graph_from_place

### ISSUE THREAD

**Issue by d3netxer** [gboeing/osmnx#110]
#### graph_from_place function not working

I am trying to follow this example in the tutorials, but it is producing errors

#### Complete list of your environment's packages

```
alabaster                 0.7.10                   py36_1    conda-forge
altair                    1.2.1                      py_0    conda-forge
appnope                   0.1.0                    py36_0    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
astroid                   1.5.3                    py36_0    conda-forge
babel                     2.5.1                    py36_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.4                      py36_1    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
branca                    0.2.0                      py_1    conda-forge
ca-certificates           2017.11.5                     0    conda-forge
certifi                   2017.11.5                py36_0    conda-forge
cffi                      1.11.2                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
curl                      7.55.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
descartes                 1.1.0                    py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.1.0                         3    conda-forge
fiona                     1.7.10                   py36_2    conda-forge
folium                    0.5.0                      py_0    conda-forge
freetype                  2.7                           2    conda-forge
freexl                    1.0.4                         0    conda-forge
gdal                      2.1.3                    py36_7    conda-forge
geopandas                 0.3.0                    py36_0    conda-forge
geopy                     1.11.0                   py36_0    conda-forge
geos                      3.6.2                         1    conda-forge
giflib                    5.1.4                         0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        1    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py36_1    conda-forge
imagesize                 0.7.1                    py36_0    conda-forge
intel-openmp              2018.0.0             h8158457_8  
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
isort                     4.2.15                   py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            2    conda-forge
json-c                    0.12.1                        0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.7                         4    conda-forge
krb5                      1.14.2                        0    conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                          0    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.28                        2    conda-forge
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.15                        1    conda-forge
libspatialindex           1.8.5                         1    conda-forge
libspatialite             4.3.0a                       18    conda-forge
libssh2                   1.8.0                         2    conda-forge
libtiff                   4.0.9                         0    conda-forge
libxml2                   2.9.5                         2    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.0                    py36_1    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
mistune                   0.8                      py36_0    conda-forge
mkl                       2018.0.1             hfbd8650_4  
munch                     2.2.0                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  2.0                      py36_0    conda-forge
notebook                  5.2.1                    py36_2    conda-forge
numpy                     1.13.3           py36h2cdce51_0  
numpydoc                  0.7.0                    py36_0    conda-forge
openjpeg                  2.1.2                         2    conda-forge
openssl                   1.0.2l                        0    conda-forge
osmnx                     0.6                      py36_1    conda-forge
pandas                    0.21.0                   py36_0    conda-forge
pandoc                    2.0.0.1                       1    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.3.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.0                    py36_0    conda-forge
psycopg2                  2.7.3.2                  py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pylint                    1.7.1                    py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysal                     1.14.3                   py36_0    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
python.app                1.2                      py36_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                h9e3eb04_4    conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.3.1                    py36_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
rope                      0.10.7                   py36_0    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
scipy                     1.0.0            py36h1de22e9_0  
setuptools                37.0.0                   py36_0    conda-forge
shapely                   1.6.2                    py36_1    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sphinx                    1.6.5                    py36_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.4                    py36_0    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   4.5.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
typing                    3.6.2                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
vega                      0.4.4                    py36_1    conda-forge
vincent                   0.4.4                    py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.30.0                     py_1    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0    conda-forge
```
#### Code that reproduces the issue

```python
import osmnx as ox
G = ox.graph_from_place('Modena, Italy', network_type='walk')
```

results in:

```
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 10.896448210936516 44.724233113679041 at 10.896448210936516 44.724233113679041
Traceback (most recent call last):

  File "<ipython-input-12-212e26f203b8>", line 1, in <module>
    G = ox.graph_from_place('Modena, Italy', network_type='walk')

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/core.py", line 1800, in graph_from_place
    clean_periphery=clean_periphery, infrastructure=infrastructure)

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/core.py", line 1678, in graph_from_polygon
    infrastructure=infrastructure)

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/core.py", line 654, in osm_net_download
    geometry_proj, crs_proj = project_geometry(polygon)

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/projection.py", line 52, in project_geometry
    gdf_proj = project_gdf(gdf, to_crs=to_crs, to_latlong=to_latlong)

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/projection.py", line 106, in project_gdf
    avg_longitude = gdf['geometry'].unary_union.centroid.x

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/geopandas/base.py", line 195, in unary_union
    return unary_union(self.geometry.values)

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/shapely/ops.py", line 150, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/shapely/geometry/base.py", line 76, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")

ValueError: No Shapely geometry can be created from null value

```

**Comment by d3netxer** [comment]
I have another example with a different error:

```
GM = ox.graph_from_place('Manhattan Island, New York, New York, USA')
```

error:

```
Traceback (most recent call last):

  File "<ipython-input-18-e38e343acfaf>", line 1, in <module>
    GM = ox.graph_from_place('Manhattan Island, New York, New York, USA')

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/core.py", line 1800, in graph_from_place
    clean_periphery=clean_periphery, infrastructure=infrastructure)

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/core.py", line 1680, in graph_from_polygon
    G_buffered = truncate_graph_polygon(G_buffered, polygon_buffered, retain_all=True, truncate_by_edge=truncate_by_edge)

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/core.py", line 1125, in truncate_graph_polygon
    points_within_geometry = intersect_index_quadrats(gdf_nodes, polygon, quadrat_width=quadrat_width, min_num=min_num, buffer_amount=buffer_amount)

  File "/Users/myusername/anaconda/envs/OSMNX/lib/python3.6/site-packages/osmnx/core.py", line 1053, in intersect_index_quadrats
    for poly in multipoly:

TypeError: 'Polygon' object is not iterable
```

**Comment by gboeing** [comment]
@d3netxer strange, none of those examples are producing errors for me. I just ran them all and they all succeeded (on Windows and Linux machines). Have you tried on any other computers?

**Comment by d3netxer** [comment]
Thanks, I will try on a different computer later this week and get back to you

**Comment by ffaristocrat** [comment]
I ended going down a rabbit hole trying to figure out the issue I was having with osmnx on OSX. It looks like there might something up with shapely on conda-forge?

These are the steps I've had success with on a fresh install of anaconda:
```
conda create --yes --name GEOTEST python=3.6
source activate GEOTEST
conda install --yes -c conda-forge --override-channels osmnx libgdal numpy scipy libgfortran ipykernel nb_conda
conda remove --yes fiona shapely
pip install fiona shapely geopandas osmnx

```

There also seems to be a problem with conda's override channels not actually installing the conda-forge version of some libraries (like fiona, libgdal, numpy & scipy) when they're dependancies.

**Comment by gboeing** [comment]
@ffaristocrat thanks. I'll leave this closed here for now as it seems to be a platform specific conda install issue rather than with the codebase in this repo. If the problem persists, please open an issue at https://github.com/conda-forge/osmnx-feedstock or the relevant dependency's feedstock repo.
