### ISSUE TITLE
Bounding Box doesn't work in ox.features_from_bbox(bbox, tags)

### ISSUE THREAD

**Issue by Gurkitier** [gboeing/osmnx#1193]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My problem is not addressed by the documentation or examples

### Existing issues

- [X] My problem does not appear in an existing issue

### What operating system and Python version are you using?

Windows10/Python 3.9.19

### What OSMnx version are you using?

1.9.3

### Environment packages and versions

```shell
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
blas                      1.0                         mkl    anaconda
blosc                     1.21.4               hdccc3a2_0    conda-forge
boost-cpp                 1.78.0               h9f4b32c_3    conda-forge
bottleneck                1.3.5            py39h080aedc_0    anaconda
branca                    0.6.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2024.6.2             h56e8100_0    conda-forge
cairo                     1.16.0            hdecc03f_1016    conda-forge
certifi                   2024.6.2           pyhd8ed1ab_0    conda-forge
cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
click-plugins             1.1.1                      py_0    anaconda
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.0.0              pyhd3eb1b0_0    anaconda
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0            py39h1f6ef14_0    conda-forge
curl                      8.1.2                h68f0423_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cykhash                   2.0.1            py39h99910a6_2    conda-forge
cython                    3.0.10           py39h99910a6_0    conda-forge
cytoolz                   0.12.0           py39h2bbff1b_0    anaconda
dask-core                 2.17.0                     py_0    anaconda
dataclasses               0.8                pyhc8e2a94_3    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
fiona                     1.9.4            py39h2bf661d_0    conda-forge
folium                    0.14.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.40.0           py39ha55989b_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
freexl                    1.0.6                h67ca5e6_1    conda-forge
gdal                      3.7.0            py39h93d52d4_2    conda-forge
geojson                   3.0.1              pyhd8ed1ab_0    conda-forge
geopandas                 0.13.2             pyhd8ed1ab_1    conda-forge
geopandas-base            0.13.2             pyha770c72_1    conda-forge
geos                      3.11.2               h1537add_0    conda-forge
geotiff                   1.7.1                h4e61e90_9    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.76.3               h12be248_0    conda-forge
glib-tools                2.76.3               h12be248_0    conda-forge
gst-plugins-base          1.22.4               h001b923_0    conda-forge
gstreamer                 1.22.4               hb4038d2_0    conda-forge
hdf4                      4.2.15               h1334946_6    conda-forge
hdf5                      1.14.0          nompi_h918d9b7_103    conda-forge
icu                       72.1                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imageio                   2.19.3           py39haa95532_0    anaconda
importlib-metadata        6.7.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          haa95532_3556    anaconda
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.1.1            py39haa95532_0    anaconda
kealib                    1.5.1                hc8369a0_3    conda-forge
kiwisolver                1.4.4            py39h1f6ef14_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libarchive                3.6.2                h6f8411a_1    conda-forge
libblas                   3.9.0           1_h8933c1f_netlib    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge
libclang                  16.0.6          default_heb8d277_0    conda-forge
libclang13                16.0.6          default_hc80b9e7_0    conda-forge
libcurl                   8.1.2                h68f0423_0    conda-forge
libdeflate                1.18                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.7.0                h32ef8ef_2    conda-forge
libglib                   2.76.3               he8f3873_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
libnetcdf                 4.9.2           nompi_ha5afab8_105    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     15.3                 ha9684e8_1    conda-forge
librttopo                 1.1.0               he1da8c1_13    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               hf8d749d_27    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.5.1                h6c8260b_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.11.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h6070c61_1    conda-forge
libzip                    1.9.2                h519de47_1    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lxml                      4.9.3            py39hbae3653_0    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.5.0              pyhd8ed1ab_1    conda-forge
markupsafe                2.1.3            py39ha55989b_0    conda-forge
matplotlib                3.7.1            py39hcbf5309_0    conda-forge
matplotlib-base           3.7.1            py39haf65ace_0    conda-forge
mkl                       2021.4.0           haa95532_640    anaconda
mkl-service               2.4.0            py39h2bbff1b_0    anaconda
mkl_fft                   1.3.1            py39h277e83a_0    anaconda
mkl_random                1.2.2            py39hf11a4ad_0    anaconda
msys2-conda-epoch         20160418                      1    conda-forge
munch                     3.0.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  2.8.4            py39haa95532_0    anaconda
numexpr                   2.8.4            py39h5b0cc5e_0    anaconda
numpy                     1.23.5           py39h3b20f71_0    anaconda
numpy-base                1.23.5           py39h4da318b_0    anaconda
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.3.1                h2466b09_1    conda-forge
osmnx                     1.9.3              pyhd8ed1ab_0    conda-forge
owslib                    0.29.2             pyhd8ed1ab_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.5.2            py39hf11a4ad_0    anaconda
pcre2                     10.40                h17e33f8_0    conda-forge
pillow                    9.5.0            py39ha9166d5_1    conda-forge
pip                       23.1.2           py39haa95532_0    anaconda
pixman                    0.40.0               h8ffe710_0    conda-forge
platformdirs              3.8.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
poppler                   23.05.0              h45d20d0_1    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.3                 h96452e4_1    conda-forge
proj                      9.2.1                h660b3b0_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pyparsing                 3.1.0              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.0            py39h1ab44e7_1    conda-forge
pyqt                      5.15.7           py39hb77abff_3    conda-forge
pyqt5-sip                 12.11.0          py39h99910a6_3    conda-forge
pyrobuf                   0.9.3            py39h99910a6_6    conda-forge
pyrosm                    0.6.2            py39h99910a6_1    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.19               h1aa4202_0
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-rapidjson          1.18             py39ha51f57c_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.7           py39haa95532_0    anaconda
pywavelets                1.4.1            py39h2bbff1b_0    anaconda
pyyaml                    6.0              py39ha55989b_5    conda-forge
qt-main                   5.15.8              h2c8576c_12    conda-forge
rasterio                  1.3.7            py39h2a7a4f8_2    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rtree                     1.0.1            py39h09fdee3_2    conda-forge
scikit-image              0.16.2           py39hf11a4ad_0    anaconda
scikit-learn              1.2.0            py39hd77b12b_0    anaconda
scipy                     1.10.1           py39hde5eda1_3    conda-forge
seaborn                   0.12.2           py39haa95532_0    anaconda
setuptools                67.8.0           py39haa95532_0    anaconda
shapely                   2.0.1            py39h4440df4_1    conda-forge
sip                       6.7.9            py39h99910a6_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1    anaconda
snappy                    1.1.10               hfb803bf_0    conda-forge
snuggs                    1.4.7                      py_0    anaconda
sqlite                    3.41.2               h2bbff1b_0    anaconda
threadpoolctl             2.2.0              pyh0d69192_0    anaconda
tiledb                    2.13.2               h3132609_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0           py39haa95532_0    anaconda
tornado                   6.3.2            py39ha55989b_0    conda-forge
typing-extensions         4.6.3                hd8ed1ab_0    conda-forge
typing_extensions         4.6.3              pyha770c72_0    conda-forge
tzdata                    2023c                h04d1e81_0    anaconda
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              15.0.0           py39ha55989b_0    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1    anaconda
vc14_runtime              14.34.31931         h5081d32_16    conda-forge
vs2015_runtime            14.34.31931         hed1258a_16    conda-forge
wheel                     0.38.4           py39haa95532_0    anaconda
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xerces-c                  3.2.4                h63175ca_2    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xyzservices               2023.7.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
```

### How did you install OSMnx?

Conda and conda-forge

### Problem description

I wanted to download features from osm data using a bounding box. It worked with using a place:  #power = ox.features_from_place(place_name, tags). It doesn't worked with power = ox.features_from_bbox(bbox, tags). I got following error message:
C:\Users\osm\AppData\Roaming\JetBrains\PyCharmCE2023.2\scratches\downloadOSMdata.py:53: FutureWarning: The `north`, `south`, `east`, and `west` parameters are deprecated and will be removed in the v2.0.0 release. Use the `bbox` parameter instead. See the OSMnx v2 migration guide: https://github.com/gboeing/osmnx/issues/1123
  power = ox.features_from_bbox(bbox, tags)
Traceback (most recent call last):
  File "C:\Users\osm\AppData\Roaming\JetBrains\PyCharmCE2023.2\scratches\downloadOSMdata.py", line 53, in <module>
    power = ox.features_from_bbox(bbox, tags)
  File "C:\Users\ogbm\.conda\envs\baum_osm\lib\site-packages\osmnx\features.py", line 131, in features_from_bbox
    polygon = utils_geo.bbox_to_poly(bbox=bbox)
  File "C:\Users\ogbm\.conda\envs\baum_osm\lib\site-packages\osmnx\utils_geo.py", line 468, in bbox_to_poly
    return Polygon([(west, south), (east, south), (east, north), (west, north)])
  File "C:\Users\ogbm\.conda\envs\baum_osm\lib\site-packages\shapely\geometry\polygon.py", line 230, in __new__
    shell = LinearRing(shell)
  File "C:\Users\ogbm\.conda\envs\baum_osm\lib\site-packages\shapely\geometry\polygon.py", line 93, in __new__
    coordinates = np.array([_coords(o) for o in coordinates])
  File "C:\Users\ogbm\.conda\envs\baum_osm\lib\site-packages\shapely\geometry\polygon.py", line 93, in <listcomp>
    coordinates = np.array([_coords(o) for o in coordinates])
  File "C:\Users\ogbm\.conda\envs\baum_osm\lib\site-packages\shapely\geometry\polygon.py", line 91, in _coords
    return [float(c) for c in o]
  File "C:\Users\ogbm\.conda\envs\baum_osm\lib\site-packages\shapely\geometry\polygon.py", line 91, in <listcomp>
    return [float(c) for c in o]
TypeError: float() argument must be a string or a number, not 'NoneType'

My bounding box looks like:
bbox = (north, south, east, west)
with 
north = 50.39412
south = 50.14115
west = 10.14022
east = 10.65932

### Complete minimal reproducible example

```python
import osmnx as ox
north = 50.39412
south = 50.14115
west = 10.14022
east = 10.65932
bbox = (north, south, east, west)
tags = {'power': 'minor_line'}
try:
    power = ox.features_from_bbox(bbox, tags)
    print("Downloaded power features:")
    print(power.head())
except TypeError as e:
    print(f"Error downloading features: {e}")
    raise
```

**Comment by gboeing** [comment]
See [the docs](https://osmnx.readthedocs.io/en/stable/user-reference.html#osmnx.features.features_from_bbox). In v1.9.x these bbox arguments are keyword arguments. If you're passing it positionally, you're passing `bbox` in the first position, which is currently the deprecated `north` argument. Just pass it by keyword. This API quirk for backwards-compatibility is cleaned up in v2.0.0 (currently in beta release).

```python
power = ox.features_from_bbox(bbox=bbox, tags=tags)
```
