### ISSUE TITLE
OSMnx docs not building on readthedocs

### ISSUE THREAD

**Issue by gboeing** [gboeing/osmnx#172]
Error message:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/osmnx/conda/latest/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/osmnx/conda/latest/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 59, in <module>
    import osmnx
  File "/home/docs/checkouts/readthedocs.org/user_builds/osmnx/checkouts/latest/osmnx/__init__.py", line 9, in <module>
    from .buildings import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/osmnx/checkouts/latest/osmnx/buildings.py", line 9, in <module>
    import geopandas as gpd
  File "/home/docs/checkouts/readthedocs.org/user_builds/osmnx/conda/latest/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/home/docs/checkouts/readthedocs.org/user_builds/osmnx/conda/latest/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/home/docs/checkouts/readthedocs.org/user_builds/osmnx/conda/latest/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/docs/checkouts/readthedocs.org/user_builds/osmnx/conda/latest/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
```

see also https://github.com/conda-forge/fiona-feedstock/issues/77

**Comment by gboeing** [comment]
Resolved by #173
