### ISSUE TITLE
b'No such file or directory'

### ISSUE THREAD

**Issue by pmartin24** [gboeing/osmnx#205]
While trying to execute the first code you posted (thanks a lot in advance), I got the following error (new to python so I don't understand the problem):

Could you help me please?

runfile('C:/Users/username/AppData/Local/Continuum/anaconda3/pkgs/osmnx-0.8.2-py_0/site-packages/osmnx/Isochrones 1.py', wdir='C:/Users/username/AppData/Local/Continuum/anaconda3/pkgs/osmnx-0.8.2-py_0/site-packages/osmnx')
Traceback (most recent call last):

  File "<ipython-input-20-48f64135d3f9>", line 1, in <module>
    runfile('C:/Users/username/AppData/Local/Continuum/anaconda3/pkgs/osmnx-0.8.2-py_0/site-packages/osmnx/Isochrones 1.py', wdir='C:/Users/username/AppData/Local/Continuum/anaconda3/pkgs/osmnx-0.8.2-py_0/site-packages/osmnx')

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/username/AppData/Local/Continuum/anaconda3/pkgs/osmnx-0.8.2-py_0/site-packages/osmnx/Isochrones 1.py", line 10, in <module>
    G = ox.graph_from_place('Manhattan Island, New York City, New York, USA', network_type='drive')

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\osmnx\core.py", line 1867, in graph_from_place
    custom_filter=custom_filter)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\osmnx\core.py", line 1733, in graph_from_polygon
    polygon_utm, crs_utm = project_geometry(geometry=polygon)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\osmnx\projection.py", line 53, in project_geometry
    gdf_proj = project_gdf(gdf, to_crs=to_crs, to_latlong=to_latlong)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\osmnx\projection.py", line 119, in project_gdf
    projected_gdf = gdf.to_crs(utm_crs)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\geopandas\geodataframe.py", line 443, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\geopandas\geoseries.py", line 304, in to_crs
    proj_in = pyproj.Proj(self.crs, preserve_units=True)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\pyproj\__init__.py", line 358, in __new__
    return _proj.Proj.__new__(self, projstring)

  File "_proj.pyx", line 84, in _proj.Proj.__cinit__

RuntimeError: b'No such file or directory'

thank you in advance

```

**Comment by gboeing** [comment]
This issue is solved here: https://github.com/gboeing/osmnx/issues/203

See here for more info: https://github.com/geopandas/geopandas/issues/830#issuecomment-426116505
