### ISSUE TITLE
AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found

### ISSUE THREAD

**Issue by GiForce** [gboeing/osmnx#3]
Hello. 
'pip install osmnx'
fails at rtree:
Collecting rtree>=0.8 (from osmnx)
  Using cached Rtree-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6g/7qfb0g056b14k5jr15p7x65r0000gs/T/pip-build-8aelx0az/rtree/setup.py", line 4, in <module>
        import rtree
      File "/private/var/folders/6g/7qfb0g056b14k5jr15p7x65r0000gs/T/pip-build-8aelx0az/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/private/var/folders/6g/7qfb0g056b14k5jr15p7x65r0000gs/T/pip-build-8aelx0az/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/private/var/folders/6g/7qfb0g056b14k5jr15p7x65r0000gs/T/pip-build-8aelx0az/rtree/rtree/core.py", line 110, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
        func = self.__getitem__(name)
      File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found

[Toblerity/rtree](https://github.com/Toblerity/rtree/pull/74) has an open issue about it, I'm running
Os X 10.12.1,  python 3.5.2.

**Comment by gboeing** [comment]
This isn't an OSMnx issue - it's an rtree issue. You might want to open an issue directly with the rtree GitHub repo. That said, you're on OS X so you may want to try to install with [conda's IOOS channel](https://anaconda.org/IOOS/rtree):
`conda install -c ioos rtree=0.8.2`

Some of my students that have macs struggled to install rtree with pip, but succeeded with that conda command. If you're on windows, you can follow these instructions to [install geopandas and rtree](http://geoffboeing.com/2014/09/using-geopandas-windows/).

**Comment by GiForce** [comment]
I just had to brew spatialindex. Excuse, I was too impatient or too lazy to read the rtree-issue precisely. Good thing I was too lazy to mind installing conda though ;)

**Comment by jasimmk** [comment]
Ran these, and it worked for me on macOs Mojave 10.14.6

```
brew install spatialindex
sudo pip3 install osmnx
```

**Comment by nate-benton90** [comment]
@jasimmk solution worked for my system and configuration - thanks.

> Details:
> macOS => Catalina /// 10.15.3

Note also that pip worked as well.
