### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qu23jn2x/Rtree/

### ISSUE THREAD

**Issue by sevku** [gboeing/osmnx#434]
```
$ pip3 install osmnx
Collecting osmnx
  Using cached https://files.pythonhosted.org/packages/d3/16/e3975ec7dbece719d825259754d708312688732444779fd7dfd99322ce40/osmnx-0.12-py2.py3-none-any.whl
Collecting pandas>=1.0 (from osmnx)
  Using cached https://files.pythonhosted.org/packages/4a/6a/94b219b8ea0f2d580169e85ed1edc0163743f55aaeca8a44c2e8fc1e344e/pandas-1.0.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting geopandas>=0.7 (from osmnx)
  Using cached https://files.pythonhosted.org/packages/83/c5/3cf9cdc39a6f2552922f79915f36b45a95b71fd343cfc51170a5b6ddb6e8/geopandas-0.7.0-py2.py3-none-any.whl
Collecting matplotlib>=3.2 (from osmnx)
  Using cached https://files.pythonhosted.org/packages/b2/c2/71fcf957710f3ba1f09088b35776a799ba7dd95f7c2b195ec800933b276b/matplotlib-3.2.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting numpy>=1.18 (from osmnx)
  Using cached https://files.pythonhosted.org/packages/e7/38/f14d6706ae4fa327bdb023ef40b4d902bccd314d886fac4031687a8acc74/numpy-1.18.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting pyproj>=2.6 (from osmnx)
  Using cached https://files.pythonhosted.org/packages/ae/d2/28fda2c7e9b43cc68837009ef6388b04499abbcfd25984ba953a2060b13d/pyproj-2.6.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting Rtree>=0.9 (from osmnx)
  Using cached https://files.pythonhosted.org/packages/56/6f/f1e91001d5ad9fa9bed65875152f5a1c7955c5763168cae309546e6e9fda/Rtree-0.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qu23jn2x/Rtree/setup.py", line 3, in <module>
        import rtree
      File "/tmp/pip-install-qu23jn2x/Rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-install-qu23jn2x/Rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-install-qu23jn2x/Rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
        func = self.__getitem__(name)
      File "/usr/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/bin/python3: undefined symbol: Error_GetLastErrorNum
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qu23jn2x/Rtree/
```

I've tried to solve it, but the things I found online didn't work for me. Maybe someone here as a solution specific to osmnx. I didn't manage to install it.

**Comment by RuiLoureiro** [comment]
Check the following similar issues: #3 , #45 

This worked for me on mac:
```
brew install spatialindex
pip3 install osmnx
```

**Comment by gboeing** [comment]
> This worked for me on mac

Thanks @RuiLoureiro. @sevku per [the documentation](https://osmnx.readthedocs.io/en/stable/):

> you can install OSMnx via pip (if you already have all of its dependencies installed on your system)

You're getting that error because you don't have the dependencies already installed on your system. RTree depends on libspatialindex, which @RuiLoureiro demonstrates how to install in advance. OSMnx is pure python, so its installation is trivially easy, but some of its dependencies have complicated installation. Using conda makes this easy, but you can try to install the dependencies manually yourself with `apt`, `brew`, similar tools, or from source.
