### ISSUE TITLE
Windows 64bit Python 2.7 RTree Error

### ISSUE THREAD

**Issue by HeikkiVesanto** [gboeing/osmnx#5]
Running through the example of:
```
import osmnx as ox
G = ox.graph_from_place('Berkeley, California', network_type='drive')
stats = ox.basic_stats(G)
ox.plot_graph(G)
```

I get an error when running in a 64bit version. I tried both a OSGeo4W python install and stand alone with the same resulting error message:

```
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
>>> import osmnx as ox
Backend TkAgg is interactive backend. Turning interactive mode on.
>>> G = ox.graph_from_place('Berkeley, California', network_type='drive')
C:\OSGeo4W64\apps\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
C:\OSGeo4W64\apps\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\osmnx\osmnx.py", line 1815, in graph_from_place
    truncate_by_edge=truncate_by_edge, name=name, timeout=timeout, memory=memory, max_query_area_size=max_query_area_size, clean_periphery=clean_periphery)
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\osmnx\osmnx.py", line 1742, in graph_from_polygon
    G_buffered = truncate_graph_polygon(G_buffered, polygon_buffered, retain_all=True, truncate_by_edge=truncate_by_edge)
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\osmnx\osmnx.py", line 1306, in truncate_graph_polygon
    points_within_geometry = intersect_index_quadrats(gdf_nodes, polygon)
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\osmnx\osmnx.py", line 1256, in intersect_index_quadrats
    sindex = gdf['geometry'].sindex
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\geopandas\base.py", line 292, in sindex
    self._generate_sindex()
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\geopandas\base.py", line 80, in _generate_sindex
    self._sindex = SpatialIndex(stream)
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\geopandas\sindex.py", line 16, in __init__
    RTreeIndex.__init__(self, *args)
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\rtree\index.py", line 179, in __init__
    self.properties = kwargs.get('properties', Property())
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\rtree\index.py", line 906, in __init__
    handle = PropertyHandle()
  File "C:\OSGeo4W64\apps\Python27\lib\site-packages\rtree\index.py", line 848, in __init__
    self._ptr = self._create(*args, **kwargs)
WindowsError: exception: access violation reading 0x0000000000224000

Exception AttributeError: "'PropertyHandle' object has no attribute '_ptr'" in <bound method PropertyHandle.__del__ of <rtree.index.PropertyHandle object at 0x0000000021A72DD8>> ignored
```

Works great in 32 bit version.

**Comment by gboeing** [comment]
It looks like this is an issue with rtree itself. Namely, its C code seems to be performing an illegal operation that throws that WindowsError. Might be worth opening an issue at the [rtree repo](https://github.com/Toblerity/rtree). 

I can confirm that everything works fine in my Python 2 test environment on Windows: 64-bit Python 2.7.12, using standalone package installations.
