### ISSUE TITLE
Install error with ValueError: unsupported format character 'B' (0x42) at index 238

### ISSUE THREAD

**Issue by envhyf** [gboeing/osmnx#50]
If you're having trouble with OSMnx, first search the previously opened issues to see if the problem has already been noted. If not, fill in the template below. You can delete any sections that don't apply.

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

<details>
# Paste the output of your Python packages and their versions here, between these two "details" tags
I have installed Anaconda with Python 2.7 in Mac OSX system. 
Using `conda install -c conda-forge osmnx`, the errors show like this:
</details>

#### Code that reproduces the issue

```shell
    Traceback (most recent call last):
      File "/Users/HYF/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/HYF/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/HYF/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/HYF/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "/Users/HYF/anaconda/lib/python2.7/site-packages/conda/__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'B' (0x42) at index 238
```

**Comment by gboeing** [comment]
If you're having trouble with OSMnx, please fill out the issue template. The only way we can troubleshoot this is if you give us full info about what's going on, including a description of the problem, your operating system and python version, and a full set of commands or code to reproduce the issue you're experiencing.

**Comment by gboeing** [comment]
Haven't heard back, so closing this for now. Feel free to re-open to post a full description of the problem, your operating system and python version, and a full set of commands or code to reproduce the issue you're experiencing.

**Comment by envhyf** [comment]
Sorry for replying late. I then have tried to install Rtree package first and then use pip install OSMnx. The problem is solved. Thanks for your great project. It really help me a lot!

**Comment by Sharonno** [comment]
I tried to install mysql by Anaconda on my Linux64 system. After running command 
`install -c CEFCA mysql-python`
I got errors below

>`Traceback (most recent call last):
      File "/home/work/tmp/anacoda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/work/tmp/anacoda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/work/tmp/anacoda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/work/tmp/anacoda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "/home/work/tmp/anacoda2/lib/python2.7/site-packages/conda/__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'B' (0x42) at index 238`

I have no idea and thank you for your help

**Comment by gboeing** [comment]
@Sharonno is this an OSMnx issue?
