### ISSUE TITLE
error with plotting using tkagg

### ISSUE THREAD

**Issue by cdbattags** [gboeing/osmnx#55]
Thanks so much in advance!

#### Problem description (what did you do, what did you expect to happen, and what actually happened)

_tkinter.TclError: no display name and no $DISPLAY environment variable

#### What operating system, architecture, Python version, and OSMnx version are you using?

```
python 3.5.2
ubuntu 16.04.2 LTS (Xenial Xerus)
OSMnx 0.5.1
```

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

```
blinker (1.3)
chardet (2.3.0)
click (6.7)
click-plugins (1.0.3)
cligj (0.4.0)
cloud-init (0.7.9)
command-not-found (0.3)
configobj (5.0.6)
cryptography (1.2.3)
cycler (0.10.0)
decorator (4.0.11)
descartes (1.1.0)
Fiona (1.7.6)
geopandas (0.2.1)
idna (2.0)
ipython (6.0.0)
ipython-genutils (0.2.0)
jedi (0.10.2)
Jinja2 (2.8)
jsonpatch (1.10)
jsonpointer (1.9)
language-selector (0.1)
MarkupSafe (0.23)
matplotlib (2.0.2)
munch (2.1.1)
networkx (1.11)
numpy (1.12.1)
oauthlib (1.0.3)
osmnx (0.5.1)
pandas (0.20.1)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (8.1.1)
prettytable (0.7.2)
prompt-toolkit (1.0.14)
ptyprocess (0.5.1)
pyasn1 (0.1.9)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
PyJWT (1.3.0)
pyparsing (2.2.0)
pyproj (1.9.5.1)
pyserial (3.0.1)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
python-debian (0.1.27)
python-systemd (231)
pytz (2017.2)
PyYAML (3.11)
requests (2.14.2)
Rtree (0.8.3)
setuptools (20.7.0)
Shapely (1.5.17.post1)
simplegeneric (0.8.1)
six (1.10.0)
ssh-import-id (5.5)
traitlets (4.3.2)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.13.1)
virtualenv (15.0.1)
wcwidth (0.1.7)
wheel (0.29.0)
```

<details>
# Paste the output of your Python packages and their versions here, between these two "details" tags

```
Configured osmnx
Projected the GeoDataFrame "geometry to project" to UTM-10 in 0.00 seconds
Projected the GeoDataFrame "geometry to project" to EPSG 4326 in 0.01 seconds
Created bounding box 966.0 meters in each direction from (37.793897, -122.402189): 37.80260328551444,37.78519070147573,-122.39121763732687,-122.41316039288394
Projected the GeoDataFrame "geometry to project" to UTM-10 in 0.00 seconds
Projected the GeoDataFrame "geometry to project" to EPSG 4326 in 0.01 seconds
Requesting network data within bounding box from API in 1 request(s)
Retrieved response from cache file "cache/42f3547b7c5fa2c8725f49fb854667d0.json" for URL "http://www.overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A180%5D%3B%28way%5B%22highway%22%5D%5B%22area%22%21~%22yes%22%5D%5B%22highway%22%21~%22cycleway%7Cfootway%7Cpath%7Cpedestrian%7Csteps%7Ctrack%7Cproposed%7Cconstruction%7Cbridleway%7Cabandoned%7Cplatform%7Craceway%22%5D%5B%22motor_vehicle%22%21~%22no%22%5D%5B%22motorcar%22%21~%22no%22%5D%5B%22access%22%21~%22private%22%5D%5B%22service%22%21~%22parking%7Cparking_aisle%7Cprivate%7Cemergency_access%22%5D%2837.78519070%2C-122.41316039%2C37.80260329%2C-122.39121764%29%3B%3E%3B%29%3Bout%3B"
Got all network data within bounding box from API in 1 request(s) and 0.03 seconds
Creating networkx graph from downloaded OSM data...
Graph was not connected, retained only the largest weakly connected component (2,033 of 2,094 total nodes) in 0.36 seconds
Created graph with 2,033 nodes and 3,220 edges in 0.44 seconds
Added edge lengths to graph in 0.06 seconds
Truncated graph by bounding box in 0.25 seconds
Removed 0 isolated nodes
Graph was not connected, retained only the largest weakly connected component (1,777 of 1,799 total nodes) in 0.25 seconds
graph_from_bbox() returning graph with 1,777 nodes and 2,913 edges
graph_from_point() returning graph with 1,777 nodes and 2,913 edges
Begin topologically simplifying the graph...
Identified 843 edge endpoints in 0.10 seconds
Constructed all paths to simplify in 0.00 seconds
Simplified graph (from 1,777 to 843 nodes and from 2,913 to 1,655 edges) in 0.37 seconds
Created a GeoDataFrame from graph in 0.28 seconds
Projected the GeoDataFrame "unnamed_nodes" to UTM-10 in 0.17 seconds
Projected the GeoDataFrame "unnamed_edges" to UTM-10 in 0.37 seconds
Extracted projected node geometries from GeoDataFrame in 0.09 seconds
Rebuilt projected graph in 3.12 seconds
Projected the GeoDataFrame "geometry to project" to UTM-10 in 0.01 seconds
Created bounding box 805 meters in each direction from (37.793897, -122.402189) and projected it: 4183921.137765114,4182311.137765114,553438.0012584254,551828.0012584254
Begin plotting the graph...
Traceback (most recent call last):
  File "one-square-mile.py", line 17, in <module>
    fig, ax = ox.plot_figure_ground(point=point, filename=place, dpi=dpi)
  File "/usr/local/lib/python3.5/dist-packages/osmnx/plot.py", line 858, in plot_figure_ground
    show=show, save=save, close=close, filename=filename, file_format=file_format, dpi=dpi)
  File "/usr/local/lib/python3.5/dist-packages/osmnx/plot.py", line 353, in plot_graph
    fig, ax = plt.subplots(figsize=(fig_width, fig_height), facecolor=bgcolor)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 1202, in subplots
    fig = figure(**fig_kw)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1871, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```
</details>

#### Code that reproduces the issue

```python
import osmnx as ox

from IPython.display import Image

# %matplotlib inline

ox.config(log_file=True, log_console=True, use_cache=True)

# configure the inline image display
img_folder = 'images'
extension = 'png'
size = 350
dpi = 90

place = 'sf'
point = (37.793897, -122.402189)
fig, ax = ox.plot_figure_ground(point=point, filename=place, dpi=dpi)
Image('{}/{}.{}'.format(img_folder, place, extension), height=size, width=size)
```

**Comment by cdbattags** [comment]
Fixed this by changing matplotlibrc file using:

`backend : agg`

Curious why it was using tkagg by default...

Any ideas?

**Comment by gboeing** [comment]
This is a platform-specific matplotlib configuration rather than an OSMnx issue. See also #33. OSMnx doesn't presume any knowledge of or configuration of your matplotlib backend. If the computer does not have a display or Xwindows (for example, if you SSH to a server), you need to [configure matplotlib accordingly](https://stackoverflow.com/a/3054314), because matplotlib chooses an Xwindows backend [by default](http://stackoverflow.com/a/37605654).
