### ISSUE TITLE
Error installing osmnx with pipenv

### ISSUE THREAD

**Issue by jamie-burks** [gboeing/osmnx#566]
We use pipenv under OSX for our Python development, but we're unable to install osmnx using pipenv (errors included below). Doc says conda is the preferred method, but can it be made to work with pipenv? We would really prefer to keep using pipenv which we have standardized on and not have one project that has to be different. I found this issue [TypeError: unhashable type: 'dict' #372](https://github.com/gboeing/osmnx/issues/372) where someone was having a different error under a pipenv install, but I'm not able to get past this pipenv install error. Any help would be appreciated.

```
% pipenv install osmnx
Installing osmnx…
Error:  An error occurred while installing osmnx!
Error text: Collecting osmnx
  Downloading osmnx-0.16.0-py2.py3-none-any.whl (87 kB)
Collecting numpy>=1.19
  Downloading numpy-1.19.2-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
Collecting Shapely>=1.7
  Downloading Shapely-1.7.1-cp38-cp38-macosx_10_9_x86_64.whl (1.0 MB)
Collecting Rtree>=0.9
  Downloading Rtree-0.9.4.tar.gz (62 kB)

    ERROR: Command errored out with exit status 1:
     command: /Users/jamie/.local/share/virtualenvs/BikePumpApi-y-K1Kf4d/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4k/m_c5978n55n9c0f69d2kbwd80000gn/T/pip-install-yci_nvi8/rtree/setup.py'"'"'; __file__='"'"'/private/var/folders/4k/m_c5978n55n9c0f69d2kbwd80000gn/T/pip-install-yci_nvi8/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4k/m_c5978n55n9c0f69d2kbwd80000gn/T/pip-pip-egg-info-hodcw5w_
         cwd: /private/var/folders/4k/m_c5978n55n9c0f69d2kbwd80000gn/T/pip-install-yci_nvi8/rtree/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4k/m_c5978n55n9c0f69d2kbwd80000gn/T/pip-install-yci_nvi8/rtree/setup.py", line 3, in <module>
        import rtree
      File "/private/var/folders/4k/m_c5978n55n9c0f69d2kbwd80000gn/T/pip-install-yci_nvi8/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/private/var/folders/4k/m_c5978n55n9c0f69d2kbwd80000gn/T/pip-install-yci_nvi8/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/private/var/folders/4k/m_c5978n55n9c0f69d2kbwd80000gn/T/pip-install-yci_nvi8/rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
        func = self.__getitem__(name)
      File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in osmnx. Report this to its maintainers.
✘ Installation Failed 

```

**Comment by gboeing** [comment]
This isn't a bug with OSMnx. Best to ask "how to" questions on StackOverflow, per the issue template.

OSMnx is pure python and trivial to install with pip *if* all its dependencies are already installed. Its dependencies, however, are not pure python and their installations are nontrivial. Hence, we support and recommend conda installation, which handles it all for you. See the [installation instructions](https://osmnx.readthedocs.io/en/stable/#installation) in the documentation. If you want to install via pip, you'll have to make sure each dependency (and all of their own dependencies) are installed and tested according to each's developer's specific instructions. The dependencies are listed in the repository's `requirements.txt` file.

**Comment by jamie-burks** [comment]
Will look into that, thanks. I see requirements.txt and requirements-dev.txt, names make intent obvious, but how are those used with Conda?

**Comment by gboeing** [comment]
> how are those used with Conda?

```
conda create --name TEST_ENV --file requirements.txt
```
