### ISSUE TITLE
Error : No distribution matching

### ISSUE THREAD

**Issue by raphadasilva** [gboeing/osmnx#6]
Good morning,

I tried to install OSMnx with pip on my Debian distro, but then I'd got this error : 

  _Could not find a version that satisfies the requirement osmnx (from versions: 0.1a1.dev6, 0.1a1.dev5, 0.1a1.dev1, 0.1a1.dev4, 0.1a1.dev2, 0.1a1.dev7, 0.1a1.dev8, 0.1a1.dev4, 0.1a1.dev3, 0.1a1.dev9, 0.1a1.dev7, 0.1a1.dev11, 0.1a1.dev10, 0.1a1.dev10, 0.1a1.dev8, 0.1a1.dev6, 0.1a1.dev11, 0.1a1.dev9, 0.1a1, 0.1a1.dev3, 0.1a1.dev2, 0.1a1, 0.1a1.dev5)
Cleaning up...
No distributions matching the version for osmnx
Storing debug log for failure in /root/.pip/pip.log_

(Geopandas is installed and works fine, I checked it before writing this issue)

**Comment by gboeing** [comment]
Can you give me your platform details? Python version, architecture, system info?

**Comment by raphadasilva** [comment]
Of course ! 

My laptop runs on Linux SMP Debian 3.16.7-ckt25-2 (kernel release 3.16.0-4-amd64), and I can switch between Python 2.7.9 and Python 3.4.2. But the error is strictly the same with sudo pip install osmnx or sudo pip3 install osmnx command.

Do you need some hardware info ?

Many thanks to you and have a nice day :-)

**Comment by gboeing** [comment]
The current OSMnx release on pypi is 0.1a1. As this is an alpha release, your system might be ignoring it if you're configured to ignore [pre-releases](https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions). 

Try: sudo pip install osmnx --pre

If that does not work, run: sudo pip install -vvv osmnx

This will provide more verbose output that you can copy and paste in here so I can see what's going on.

**Comment by raphadasilva** [comment]
Thanks for new commands !

Unfortunately, one worked...

Here's the log for the command with --pre : 
```
Downloading/unpacking osmnx
  Downloading OSMnx-0.1a1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): geopy>=1.11 in /usr/local/lib/python3.4/dist-packages (from osmnx)
Downloading/unpacking matplotlib>=1.5 (from osmnx)
  Downloading matplotlib-2.0.0b4.tar.gz (53.3MB): 53.3MB downloaded
  Running setup.py (path:/tmp/pip-build-_kg3d9v3/matplotlib/setup.py) egg_info for package matplotlib
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [2.0.0b4]
                    python: yes [3.4.2 (default, Oct  8 2014, 10:45:20)  [GCC
                            4.9.1]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.8.2]
                       six: yes [The installed version of six is 1.8.0 but a the
                            minimum required version is 1.10. pip/easy install
                            will attempt to install a newer version.]
                  dateutil: yes [using dateutil version 2.2]
               functools32: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [using pytz version 2012c]
                    cycler: yes [cycler was not found. pip will attempt to
                            install it after matplotlib.]
                   tornado: yes [using tornado version 3.2.2]
                 pyparsing: yes [using pyparsing version 2.0.3]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: yes [version 2.5.2]
                       png: yes [version 1.2.50]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: yes [using nose version 1.3.4 / using unittest.mock]
            toolkits_tests: yes [using nose version 1.3.4 / using unittest.mock]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
    /usr/local/lib/python3.4/dist-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
      "Cython.Distutils.old_build_ext does not properly handle dependencies "
                    qt5agg: no  [PyQt5 not found]
                    qt4agg: yes [installing, Qt: 4.8.6, PySide: 1.2.2; PyQt4 not
                            found]
    No protocol specified
    
    ** (-c:1811): WARNING **: Could not open X display
    No protocol specified
    Unable to init server: Impossible de se connecter : Connexion refusée
    No protocol specified
    Unable to init server: Impossible de se connecter : Connexion refusée
                   gtk3agg: yes [installing, version 3.5.14]
    No protocol specified
    
    ** (-c:1819): WARNING **: Could not open X display
    No protocol specified
    Unable to init server: Impossible de se connecter : Connexion refusée
    No protocol specified
    Unable to init server: Impossible de se connecter : Connexion refusée
                 gtk3cairo: yes [installing, version 3.5.14]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: yes [installing, pycairo version 1.10.0]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: yes [version 1.14]
               ghostscript: yes [version 9.06]
                     latex: yes [version 3.14159265]
                   pdftops: yes [version 0.26.5]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    
Downloading/unpacking requests>=2.11 (from osmnx)
  Downloading requests-2.12.1-py2.py3-none-any.whl (574kB): 574kB downloaded
Downloading/unpacking shapely>=1.5 (from osmnx)
  Downloading Shapely-1.6a2.tar.gz (212kB): 212kB downloaded
  Running setup.py (path:/tmp/pip-build-_kg3d9v3/shapely/setup.py) egg_info for package shapely
    /usr/local/lib/python3.4/dist-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
      "Cython.Distutils.old_build_ext does not properly handle dependencies "
    
Downloading/unpacking rtree>=0.8 (from osmnx)
  Downloading Rtree-0.8.2.tar.gz (55kB): 55kB downloaded
  Running setup.py (path:/tmp/pip-build-_kg3d9v3/rtree/setup.py) egg_info for package rtree
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-_kg3d9v3/rtree/setup.py", line 4, in <module>
        import rtree
      File "/tmp/pip-build-_kg3d9v3/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-build-_kg3d9v3/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-build-_kg3d9v3/rtree/rtree/core.py", line 110, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
        func = self.__getitem__(name)
      File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/bin/python3: undefined symbol: Error_GetLastErrorNum
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-_kg3d9v3/rtree/setup.py", line 4, in <module>

    import rtree

  File "/tmp/pip-build-_kg3d9v3/rtree/rtree/__init__.py", line 1, in <module>

    from .index import Rtree

  File "/tmp/pip-build-_kg3d9v3/rtree/rtree/index.py", line 6, in <module>

    from . import core

  File "/tmp/pip-build-_kg3d9v3/rtree/rtree/core.py", line 110, in <module>

    rt.Error_GetLastErrorNum.restype = ctypes.c_int

  File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__

    func = self.__getitem__(name)

  File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__

    func = self._FuncPtr((name_or_ordinal, self))

AttributeError: /usr/bin/python3: undefined symbol: Error_GetLastErrorNum

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-_kg3d9v3/rtree
Storing debug log for failure in /root/.pip/pip.log
```
And here the -vvv version : 
```
Downloading/unpacking osmnx
  Getting page https://pypi.python.org/simple/osmnx/
  URLs to search for versions for osmnx:
  * https://pypi.python.org/simple/osmnx/
  Analyzing links from page https://pypi.python.org/simple/osmnx/
    Found link https://pypi.python.org/packages/02/93/437e7073df2332f17582e86a460cdffe0c89cc1092eecd6206349c22e67a/OSMnx-0.1a1.dev6.tar.gz#md5=31dc8bd743f3b3917ef3a7a85760193e (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev6
    Found link https://pypi.python.org/packages/05/94/0eb9681f3eb312023b7db4c4985569820a2e71b4331d8fe9e0dcb9b6283a/OSMnx-0.1a1.dev5-py2.py3-none-any.whl#md5=138ed6e79d26d0d2626d409a82a0b5d8 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev5
    Found link https://pypi.python.org/packages/3d/e3/ba2d1db1d32f8858c4fa26a3630b40d03024da870dfd5a72171ba7f63353/OSMnx-0.1a1.dev1.tar.gz#md5=99890e6a14d66849c6c16af77f657cd1 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev1
    Found link https://pypi.python.org/packages/46/da/bb9a33f782ded45ccce8f206257ec5cea8bb281f5f6f119f95179e934acd/OSMnx-0.1a1.dev4-py2.py3-none-any.whl#md5=8407498f769269e2a5cae304e7d4e325 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev4
    Found link https://pypi.python.org/packages/49/1b/f3e671669227bb9b7f97ce5f49eb9acfd3b5fcf258695e59a883c9249a7d/OSMnx-0.1a1.dev2-py2.py3-none-any.whl#md5=78e759e4962a12cf4b696a53d707f88e (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev2
    Found link https://pypi.python.org/packages/56/ec/2a77df36b395f4590765f3ca57d9d6d173f9142be35747a84abec9622fc8/OSMnx-0.1a1.dev7-py2.py3-none-any.whl#md5=922f5af1e681eee63c7edc166cb418bd (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev7
    Found link https://pypi.python.org/packages/5f/83/501f83807f145df67a20d921f35e4e23eeea83d675b3aa55cc78ba8ff6d4/OSMnx-0.1a1.dev8-py2.py3-none-any.whl#md5=7e9af6feb7967ba7b0080b2287dc7233 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev8
    Found link https://pypi.python.org/packages/66/91/53b4a8d1dc873e48030be64da82111db2b79de65db8326290a386623bf31/OSMnx-0.1a1.dev4.tar.gz#md5=b15b539227a1bac3f43f032465efd42f (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev4
    Found link https://pypi.python.org/packages/67/b6/7536ed5e0a1c238fa1a08082af03877665b51dba0e29ca46f8ba7b09eff1/OSMnx-0.1a1.dev3.tar.gz#md5=1b7e622f1e68b8d030cfed8eff48ce48 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev3
    Found link https://pypi.python.org/packages/79/14/977ec401c129abcbf4f60dc2a34dcb63b9a1761e2c5ad9b4f8cb26e978e2/OSMnx-0.1a1.dev9-py2.py3-none-any.whl#md5=b5d1e9ca78d336003a746da2f3253e3b (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev9
    Found link https://pypi.python.org/packages/7a/9c/829741ce57a766da4cc766ad85d870af8393f67b92d979b85160bd636ca6/OSMnx-0.1a1.dev7.tar.gz#md5=c078e2f8788443665feb34eb5f070186 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev7
    Found link https://pypi.python.org/packages/7f/d8/51eaf26ed1f8e478aac3bc2e9dd3d6941fffcb96f197c617ebac5fb70d58/OSMnx-0.1a1.dev11-py2.py3-none-any.whl#md5=ccebbd7fcfd8516c006335aaa1727377 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev11
    Found link https://pypi.python.org/packages/8f/b9/5e6ed9f510ebeb8e541464169b0b4dfebd89fb57094962dd647944f40a8e/OSMnx-0.1a1.dev10-py2.py3-none-any.whl#md5=439536bf4663682211df244f117cba49 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev10
    Found link https://pypi.python.org/packages/99/b9/f41eb8c52c2d472ae28695028b773116a5a4e4cde16406465db02d00a98c/OSMnx-0.1a1.dev10.tar.gz#md5=e7b49aec854f929034fd7ce2ed75bbab (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev10
    Found link https://pypi.python.org/packages/a4/45/e33d857666d50dce4a68b01db4433a59e974b3caeb28aca5845f49c4219d/OSMnx-0.1a1.dev8.tar.gz#md5=3852cbc221e98e7ab5d1a7ca86469e5e (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev8
    Found link https://pypi.python.org/packages/ac/cc/d2798bfa8070343fde8e46d5192ec2e9941124cd7568b70d0afb35d690e8/OSMnx-0.1a1.dev6-py2.py3-none-any.whl#md5=7bc3c6563dd838296666c03d69890be7 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev6
    Found link https://pypi.python.org/packages/af/81/6b6b6159665e5c0c9652e0ba502a42af1f61a7da9a1f391fc7dc8ef99e61/OSMnx-0.1a1.dev11.tar.gz#md5=19b6349a5be52570b25ca96d2f6da370 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev11
    Found link https://pypi.python.org/packages/bb/66/47d8213727e772197707804ff25e582d65500fa1d87e5891457815ead079/OSMnx-0.1a1.dev9.tar.gz#md5=004d7ea2d90b1c229ea22eb8bf5f2d7a (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev9
    Found link https://pypi.python.org/packages/c9/5c/6a582c29df55c6d1d2a3528a692c705de4ad6db636cee7c4d9dbc03e54f4/OSMnx-0.1a1.tar.gz#md5=44ee479f5b7e9f8c67394a057b7c8e58 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1
    Found link https://pypi.python.org/packages/cc/34/3ca691144688c58790fd090186db2d5b4f1c2f4d15ae89bcff145daf9285/OSMnx-0.1a1.dev3-py2.py3-none-any.whl#md5=6edfdea3c87e3248e9e407eb1961cf2e (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev3
    Found link https://pypi.python.org/packages/cd/f6/17729ae1989c73447333ff9f9b517dc80239c81521b5ca46cb2519907f5c/OSMnx-0.1a1.dev2.tar.gz#md5=71d7dcffcc7a1388a876f6536b85cf63 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev2
    Found link https://pypi.python.org/packages/e8/cc/c4787615c6dfab28dc6b26d64e7d69c03f194a2766f605b9d47c1e194e58/OSMnx-0.1a1-py2.py3-none-any.whl#md5=76cd1cdec7fff31456e09e104a6459d2 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1
    Found link https://pypi.python.org/packages/ed/96/926a8f6bd016e9231b2655319b57bb8f8fed7eaa8743a188fbc7e1c821f1/OSMnx-0.1a1.dev5.tar.gz#md5=7f420d4eb25598643837c15e5ae8d784 (from https://pypi.python.org/simple/osmnx/), version: 0.1a1.dev5
  Ignoring link https://pypi.python.org/packages/02/93/437e7073df2332f17582e86a460cdffe0c89cc1092eecd6206349c22e67a/OSMnx-0.1a1.dev6.tar.gz#md5=31dc8bd743f3b3917ef3a7a85760193e (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev6 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/05/94/0eb9681f3eb312023b7db4c4985569820a2e71b4331d8fe9e0dcb9b6283a/OSMnx-0.1a1.dev5-py2.py3-none-any.whl#md5=138ed6e79d26d0d2626d409a82a0b5d8 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev5 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/3d/e3/ba2d1db1d32f8858c4fa26a3630b40d03024da870dfd5a72171ba7f63353/OSMnx-0.1a1.dev1.tar.gz#md5=99890e6a14d66849c6c16af77f657cd1 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/46/da/bb9a33f782ded45ccce8f206257ec5cea8bb281f5f6f119f95179e934acd/OSMnx-0.1a1.dev4-py2.py3-none-any.whl#md5=8407498f769269e2a5cae304e7d4e325 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev4 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/49/1b/f3e671669227bb9b7f97ce5f49eb9acfd3b5fcf258695e59a883c9249a7d/OSMnx-0.1a1.dev2-py2.py3-none-any.whl#md5=78e759e4962a12cf4b696a53d707f88e (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/56/ec/2a77df36b395f4590765f3ca57d9d6d173f9142be35747a84abec9622fc8/OSMnx-0.1a1.dev7-py2.py3-none-any.whl#md5=922f5af1e681eee63c7edc166cb418bd (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev7 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/5f/83/501f83807f145df67a20d921f35e4e23eeea83d675b3aa55cc78ba8ff6d4/OSMnx-0.1a1.dev8-py2.py3-none-any.whl#md5=7e9af6feb7967ba7b0080b2287dc7233 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev8 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/66/91/53b4a8d1dc873e48030be64da82111db2b79de65db8326290a386623bf31/OSMnx-0.1a1.dev4.tar.gz#md5=b15b539227a1bac3f43f032465efd42f (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev4 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/67/b6/7536ed5e0a1c238fa1a08082af03877665b51dba0e29ca46f8ba7b09eff1/OSMnx-0.1a1.dev3.tar.gz#md5=1b7e622f1e68b8d030cfed8eff48ce48 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev3 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/79/14/977ec401c129abcbf4f60dc2a34dcb63b9a1761e2c5ad9b4f8cb26e978e2/OSMnx-0.1a1.dev9-py2.py3-none-any.whl#md5=b5d1e9ca78d336003a746da2f3253e3b (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev9 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/7a/9c/829741ce57a766da4cc766ad85d870af8393f67b92d979b85160bd636ca6/OSMnx-0.1a1.dev7.tar.gz#md5=c078e2f8788443665feb34eb5f070186 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev7 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/7f/d8/51eaf26ed1f8e478aac3bc2e9dd3d6941fffcb96f197c617ebac5fb70d58/OSMnx-0.1a1.dev11-py2.py3-none-any.whl#md5=ccebbd7fcfd8516c006335aaa1727377 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev11 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/8f/b9/5e6ed9f510ebeb8e541464169b0b4dfebd89fb57094962dd647944f40a8e/OSMnx-0.1a1.dev10-py2.py3-none-any.whl#md5=439536bf4663682211df244f117cba49 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev10 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/99/b9/f41eb8c52c2d472ae28695028b773116a5a4e4cde16406465db02d00a98c/OSMnx-0.1a1.dev10.tar.gz#md5=e7b49aec854f929034fd7ce2ed75bbab (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev10 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/a4/45/e33d857666d50dce4a68b01db4433a59e974b3caeb28aca5845f49c4219d/OSMnx-0.1a1.dev8.tar.gz#md5=3852cbc221e98e7ab5d1a7ca86469e5e (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev8 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/ac/cc/d2798bfa8070343fde8e46d5192ec2e9941124cd7568b70d0afb35d690e8/OSMnx-0.1a1.dev6-py2.py3-none-any.whl#md5=7bc3c6563dd838296666c03d69890be7 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev6 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/af/81/6b6b6159665e5c0c9652e0ba502a42af1f61a7da9a1f391fc7dc8ef99e61/OSMnx-0.1a1.dev11.tar.gz#md5=19b6349a5be52570b25ca96d2f6da370 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev11 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/bb/66/47d8213727e772197707804ff25e582d65500fa1d87e5891457815ead079/OSMnx-0.1a1.dev9.tar.gz#md5=004d7ea2d90b1c229ea22eb8bf5f2d7a (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev9 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/c9/5c/6a582c29df55c6d1d2a3528a692c705de4ad6db636cee7c4d9dbc03e54f4/OSMnx-0.1a1.tar.gz#md5=44ee479f5b7e9f8c67394a057b7c8e58 (from https://pypi.python.org/simple/osmnx/), version 0.1a1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/cc/34/3ca691144688c58790fd090186db2d5b4f1c2f4d15ae89bcff145daf9285/OSMnx-0.1a1.dev3-py2.py3-none-any.whl#md5=6edfdea3c87e3248e9e407eb1961cf2e (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev3 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/cd/f6/17729ae1989c73447333ff9f9b517dc80239c81521b5ca46cb2519907f5c/OSMnx-0.1a1.dev2.tar.gz#md5=71d7dcffcc7a1388a876f6536b85cf63 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/e8/cc/c4787615c6dfab28dc6b26d64e7d69c03f194a2766f605b9d47c1e194e58/OSMnx-0.1a1-py2.py3-none-any.whl#md5=76cd1cdec7fff31456e09e104a6459d2 (from https://pypi.python.org/simple/osmnx/), version 0.1a1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/ed/96/926a8f6bd016e9231b2655319b57bb8f8fed7eaa8743a188fbc7e1c821f1/OSMnx-0.1a1.dev5.tar.gz#md5=7f420d4eb25598643837c15e5ae8d784 (from https://pypi.python.org/simple/osmnx/), version 0.1a1.dev5 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement osmnx (from versions: 0.1a1.dev6, 0.1a1.dev5, 0.1a1.dev1, 0.1a1.dev4, 0.1a1.dev2, 0.1a1.dev7, 0.1a1.dev8, 0.1a1.dev4, 0.1a1.dev3, 0.1a1.dev9, 0.1a1.dev7, 0.1a1.dev11, 0.1a1.dev10, 0.1a1.dev10, 0.1a1.dev8, 0.1a1.dev6, 0.1a1.dev11, 0.1a1.dev9, 0.1a1, 0.1a1.dev3, 0.1a1.dev2, 0.1a1, 0.1a1.dev5)
Cleaning up...
No distributions matching the version for osmnx
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
pip.exceptions.DistributionNotFound: No distributions matching the version for osmnx

Storing debug log for failure in /root/.pip/pip.log
```
I'm sorry, it's quite long... But hope that could help !

**Comment by gboeing** [comment]
Ok, this is getting clearer now. There are two issues. The first was what I suspected: you needed to use the pre-release flag (`sudo pip install osmnx --pre`) to get OSMnx, given your configuration. That worked. But it revealed a new issue: your machine failed to install one of the dependencies, [rtree](http://toblerity.org/rtree/install.html). Try to install rtree first, per the developer's instructions in that link. Then try to install OSMnx again with the --pre command. If another dependency fails in the future, just install that dependency first according to its developer's instructions. When all the dependencies are installed, OSMnx should install like a piece of cake because it is pure Python - nothing to compile, etc.

**Comment by raphadasilva** [comment]
Wonderful ! I do my best to quickly install rtree on my laptop, and I come back here once it's done :-)

Thank you again

**Comment by raphadasilva** [comment]
_Voilà_, installation worked :-) !

It's strange, because the basic example with Modena brings me an error, but that's not the subject of the issue... Module is correctly imported !

Thanks again.
