### ISSUE TITLE
Cannot load XML made with osmosis with --bounding-polygon option

### ISSUE THREAD

**Issue by meitiv-tti** [gboeing/osmnx#662]
**Problem description
  - Called osmnx.graph_from_xml() on an osm file created with the osmosis tool using a --bounding-polygon option (graph loads fine without polygon clipping).  The resulting osm XML seems to be valid because osmosis and osmconvert can read and manipulate it.
  - Expect: Return a MultiDiGraph object
  - Get an error: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/osmnx/graph.py", line 494, in graph_from_xml
    G = _create_graph(response_jsons, bidirectional=bidirectional, retain_all=retain_all)
  File "/usr/local/lib/python3.8/dist-packages/osmnx/graph.py", line 563, in _create_graph
    G = utils_graph.add_edge_lengths(G)
  File "/usr/local/lib/python3.8/dist-packages/osmnx/utils_graph.py", line 185, in add_edge_lengths
    df = pd.DataFrame(coords, columns=cols).set_index(["u", "v", "k"])
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 502, in __init__
    data = list(data)
  File "/usr/local/lib/python3.8/dist-packages/osmnx/utils_graph.py", line 177, in <genexpr>
    (u, v, k, G.nodes[u]["y"], G.nodes[u]["x"], G.nodes[v]["y"], G.nodes[v]["x"])
KeyError: 'y'

**Environment information**
  - Linux Mint 20 Uliyana
  - Python 3.8
  - OSMnx version 1.0.1
  - All packages
<details>
Package                Version             
---------------------- --------------------
affine                 2.3.0               
aiobotocore            1.1.2               
aiohttp                3.7.3               
aioitertools           0.7.1               
apt-clone              0.2.1               
apturl                 0.5.2               
async-timeout          3.0.1               
atomicwrites           1.1.5               
attrs                  20.3.0              
beautifulsoup4         4.8.2               
blinker                1.4                 
boto3                  1.16.30             
botocore               1.19.30             
branca                 0.4.2               
Brlapi                 0.7.0               
catfish                1.4.13              
ccsm                   0.9.14.1            
certifi                2019.11.28          
chardet                3.0.4               
Click                  7.0                 
click-plugins          1.1.1               
cligj                  0.7.1               
colorama               0.4.3               
command-not-found      0.3                 
compizconfig-python    0.9.14.1            
configobj              5.0.6               
configparser           5.0.1               
contextily             1.1.0               
cryptography           2.8                 
cupshelpers            1.0                 
cycler                 0.10.0              
dbus-python            1.2.16              
decorator              4.4.2               
defer                  1.0.6               
descartes              1.1.0               
distro                 1.4.0               
docopt                 0.6.2               
docutils               0.15.2              
entrypoints            0.3                 
Fiona                  1.8.18              
Flask                  1.1.2               
folium                 0.12.1              
fsspec                 0.8.4               
GDAL                   3.0.4               
geographiclib          1.50                
geopandas              0.8.2               
geopy                  2.1.0               
gitdb                  4.0.5               
GitPython              3.1.11              
googlemaps             4.4.2               
grip                   4.5.2               
grpcio                 1.16.1              
html2text              2020.1.16           
httplib2               0.14.0              
idna                   2.8                 
ifaddr                 0.1.6               
importlib-metadata     1.5.0               
itsdangerous           1.1.0               
Jinja2                 2.11.3              
jmespath               0.10.0              
joblib                 0.17.0              
keyring                18.0.1              
kiwisolver             1.3.1               
language-selector      0.1                 
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
louis                  3.12.0              
lxml                   4.6.2               
Mako                   1.1.0               
Markdown               3.3.3               
MarkupSafe             1.1.0               
matplotlib             3.3.4               
menulibre              2.2.1               
mercantile             1.1.6               
more-itertools         4.2.0               
mugshot                0.4.2               
multidict              5.1.0               
munch                  2.5.0               
netifaces              0.10.4              
networkx               2.5                 
nose                   1.3.7               
numpy                  1.20.1              
oauthlib               3.1.0               
onboard                1.4.1               
openrouteservice       2.3.3               
osmnx                  1.0.1               
packaging              20.3                
PAM                    0.4.2               
pandas                 1.1.4               
path-and-address       2.0.1               
pexpect                4.6.0               
Pillow                 7.0.0               
pip                    20.0.2              
pluggy                 0.13.0              
pomegranate            0.12.0              
progress               1.5                 
protobuf               3.6.1               
psutil                 5.5.1               
py                     1.8.1               
pyasn1                 0.4.8               
pycairo                1.16.2              
pycrypto               2.6.1               
pycups                 1.9.73              
pycurl                 7.43.0.2            
pygeos                 0.9+2.g0dfbd84      
Pygments               2.8.0               
PyGObject              3.36.0              
PyICU                  2.4.2               
PyJWT                  1.7.1               
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
pyparsing              2.4.6               
pyparted               3.11.2              
pyproj                 3.0.0.post1         
pytest                 4.6.9               
python-apt             2.0.0+ubuntu0.20.4.4
python-dateutil        2.8.1               
python-debian          0.1.36ubuntu1       
python-xapp            2.0.1               
pytz                   2020.4              
pyxdg                  0.26                
PyYAML                 5.3.1               
rasterio               1.2.0               
reportlab              3.5.34              
requests               2.25.1              
requests-unixsocket    0.2.0               
rsa                    4.5                 
Rtree                  0.9.4               
s3fs                   0.4.2               
s3transfer             0.3.3               
scipy                  1.5.4               
SecretStorage          2.3.1               
setproctitle           1.1.10              
setuptools             45.2.0              
Shapely                1.7.1               
simplejson             3.16.0              
six                    1.14.0              
smart-open             4.0.1               
smmap                  3.0.4               
snuggs                 1.4.7               
sortedcontainers       2.3.0               
soupsieve              1.9.5               
ssh-import-id          5.10                
systemd-python         234                 
typing-extensions      3.7.4.3             
ubuntu-advantage-tools 20.3                
ubuntu-drivers-common  0.0.0               
ufw                    0.36                
urllib3                1.25.8              
wadllib                1.3.3               
wcwidth                0.1.8               
Werkzeug               1.0.1               
wheel                  0.34.2              
wptools                0.4.17              
wrapt                  1.12.1              
xkit                   0.0.0               
xlrd                   1.2.0               
yarl                   1.6.3               
zeroconf               0.24.4              
zipp                   1.0.0               
</details>

**Example

**
```
$ osmosis --read-pbf planet.pbf --bounding-polygon file=texas.poly --tf accept-ways highway=motorway --write-xml texas_motorway.osm
```
```python
import osmnx
g = osmnx.graph_from_xml('texas_motorway.osm')
```

**Comment by meitiv-tti** [comment]
It's the issue with the XML after all.  When I use --compete-ways with osmconvert like so
```
$ osmconvert planet.osm -B=texas.poly --complete-ways -o=texas_motorway.osm
```
the resulting XML is loaded fine by osmnx.graph_from_xml()
