### ISSUE TITLE
I use graph_from_point but get an IndexError

### ISSUE THREAD

**Issue by VittorioYan** [gboeing/osmnx#732]
Here is my code.
I watch the doc and try to get the road arround a point.

```python
import networkx as nx
import osmnx as ox
from typing import Tuple
# %matplotlib inline
ox.config(log_console=True)
ox.__version__

# download/model a street network for some city then visualize it
center =(121.489747,31.238917)
G = ox.graph_from_point(center)
```
 And the error:
``` python
Traceback (most recent call last):
  File "/Users/vittorio/Desktop/tianrang/code/pfms/test3.py", line 11, in <module>
    G = ox.graph_from_point(center,dist=1000)
  File "/Users/vittorio/Desktop/tianrang/code/pfms/venv/lib/python3.7/site-packages/osmnx/graph.py", line 166, in graph_from_point
    custom_filter=custom_filter,
  File "/Users/vittorio/Desktop/tianrang/code/pfms/venv/lib/python3.7/site-packages/osmnx/graph.py", line 88, in graph_from_bbox
    custom_filter=custom_filter,
  File "/Users/vittorio/Desktop/tianrang/code/pfms/venv/lib/python3.7/site-packages/osmnx/graph.py", line 420, in graph_from_polygon
    response_jsons = downloader._osm_network_download(poly_buff, network_type, custom_filter)
  File "/Users/vittorio/Desktop/tianrang/code/pfms/venv/lib/python3.7/site-packages/osmnx/downloader.py", line 502, in _osm_network_download
    polygon_coord_strs = _make_overpass_polygon_coord_strs(polygon)
  File "/Users/vittorio/Desktop/tianrang/code/pfms/venv/lib/python3.7/site-packages/osmnx/downloader.py", line 392, in _make_overpass_polygon_coord_strs
    geometry_proj, crs_proj = projection.project_geometry(polygon)
  File "/Users/vittorio/Desktop/tianrang/code/pfms/venv/lib/python3.7/site-packages/osmnx/projection.py", line 60, in project_geometry
    gdf_proj = project_gdf(gdf, to_crs=to_crs, to_latlong=to_latlong)
  File "/Users/vittorio/Desktop/tianrang/code/pfms/venv/lib/python3.7/site-packages/osmnx/projection.py", line 109, in project_gdf
    avg_lng = gdf["geometry"].unary_union.centroid.x
  File "/Users/vittorio/Desktop/tianrang/code/pfms/venv/lib/python3.7/site-packages/shapely/geometry/point.py", line 55, in x
    return self.coords[0][0]
IndexError: list index out of range
```
I want to know if I did someting wrong.
By the way, I try to print this "self.coords" and find it has only one dimision. 
```python
print('----------------',self.coords[0])
# ---------------- (31.238917000000004, 121.48974699999998)
```
Version=1.1.1

**Comment by gboeing** [comment]
Check the [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.graph.graph_from_point):

> center_point (tuple) – the (lat, lng) center point around which to construct the graph

You are providing the point's coordinates as (lng, lat) rather than (lat, lng), which makes for an impossible geometry that blows up the processing.
