### ISSUE TITLE
AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found

### ISSUE THREAD

**Issue by quanghuyle3** [gboeing/osmnx#736]
I have installed this OSMnx package on my current python, but whenever I import it, it always gives me the same problem.
Traceback (most recent call last):
  File "/Users/qle/Documents/OSMnx/test.py", line 1, in <module>
    import osmnx as ox
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/osmnx/__init__.py", line 3, in <module>
    from ._api import *
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/osmnx/_api.py", line 3, in <module>
    from .bearing import add_edge_bearings
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/osmnx/bearing.py", line 9, in <module>
    from . import projection
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/osmnx/projection.py", line 3, in <module>
    import geopandas as gpd
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/geopandas/_config.py", line 126, in <module>
    default_value=_default_use_pygeos(),
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/geopandas/_config.py", line 112, in _default_use_pygeos
    import geopandas._compat as compat
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/geopandas/_compat.py", line 202, in <module>
    import rtree  # noqa
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/rtree/__init__.py", line 9, in <module>
    from .index import Rtree, Index  # noqa
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/rtree/index.py", line 6, in <module>
    from . import core
  File "/Users/qle/Library/Python/3.8/lib/python/site-packages/rtree/core.py", line 77, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found

I saw someone has posted about this problem and the author suggested installing a new version rtree. Well, I did try but it still gives me back this error. Please advise me with some possible steps that I should take to solve this problem if anyone knows. Thank you!

**Comment by gboeing** [comment]
Did you follow the documented installation instructions? https://osmnx.readthedocs.io/en/stable/#installation

**Comment by quanghuyle3** [comment]
The problem has been solved completely.
https://stackoverflow.com/questions/68464704/attributeerror-dlsymrtld-default-error-getlasterrornum-symbol-not-found/68477357#68477357
